name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: hadevyi/.github/.github/workflows/reusable-astro-pages.yml@main
    with:
      public-ga-id: ${{ vars.PUBLIC_GA_ID }}
      public-google-site-verification: ${{ vars.PUBLIC_GOOGLE_SITE_VERIFICATION }}
